import './globals.css';

import type { Metadata } from 'next';
import { Maven_Pro } from 'next/font/google';

import { Toaster } from '@/components/ui/Toast/Toaster';

const mavenPro = Maven_Pro({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pl">
            <body className={mavenPro.className}>
                {children}
                <Toaster />
            </body>
        </html>
    );
}
